### ISSUE TITLE
How to refetch 'atomWithQuery' ?

### ISSUE THREAD

**Issue by drMonro** [jotaijs/jotai-trpc#11]
Hello!
How I can refetch 'atomWithQuery' ?
Example:

I got that assync GET atom which is constructed to get category dynamicly from showcaseCurrentActiveCategoryAtom  : 
`

       export const showcaseCurrentActiveCategoryAtom = atom({
          class: 'showcase-categories__item--all',
          metaTitle: 'Fruits',
        })

      const getRandomOffersByCategoryAtom = api.offers.randomByCategory.atomWithQuery((get) => {
              return {
                           count: 25,
                           category: get(showcaseCurrentActiveCategoryAtom).metaTitle,
                          }
      })

`

I want to fetch what query on page, and in some moment to refetch it again after changing showcaseCurrentActiveCategoryAtom.
How can i do that?
If i do like that in click event it did't tefetch - it just make query with default value:
`

      const [randomOffersByCategory] = useAtom(getRandomOffersByCategoryAtom)

      const onCategoryClick = async () => {

       setShowcaseCurrentActiveCategory({ class: item.class, metaTitle: item.title })
       
       setShowcaseOffers(randomOffersByCategory.data)
      }
`

**Comment by drMonro** [comment]
Think I got it - just put 'howcaseCurrentActiveCategory' in useEffect deps and call 'randomOffersByCategory' there

**Comment by dai-shi** [comment]
Yeah, jotai-trpc itself doesn't have a capability of imperative refetching.

We can do atomWithRefresh pattern.
https://jotai.org/docs/recipes/atom-creators#atomwithrefresh
