### ISSUE TITLE
Mutation

### ISSUE THREAD

**Issue by drMonro** [jotaijs/jotai-trpc#15]
How to make custom mutation?
I just want to call [mutation ](https://prnt.sc/HsLxTnmfOdth )with [signing only 'offerId'](https://prnt.sc/C5mPm02rGnuD) and setting 'cartId' in Atoms layer?
Now i got [TS error ](https://prnt.sc/8uEDIylo2PdH)

How to fix? Or i missing something? Thx

**Comment by dai-shi** [comment]
Can you reproduce it in https://www.typescriptlang.org/play ? You can import libraries there.

**Comment by drMonro** [comment]
[Line 134](https://www.typescriptlang.org/play?#code/PTAEEsFsAcHsCcAuoDepoFcBGAbcBjABXlnwFMATDeM0AX1ADMTJQByAOg+EXmnzYAoQVDhJQAZwzQy8AFYTYAOyYt2UmfMVKhImAmQAqUAEMJoAJ7TVsVmyvQhog6ghLwiACoAlQgGEAGlAffwBReBJ4ehs7AAFefmAJWQA3WSd9cTRECxlQAGUyCQlwZWjmW3YlMgAPRABaEwxEAAsMsWRs3No-GhNEMgA5WsQ-ZQG6gHloRFKlcwYKuIT8JNTZYBMKExnZCWBquvaXHLy0AHEyREL4NPh88AoyYlhoCTGlCeRFtTZDxGOWVAAHMrjc7oVinMgqdaMM6gBBZotaazZQSGHdUAAETIjCaOGuRRKZR+lT+I0ayN0sNAvTI-TIHy+qLm5gAvKhBKBJMS5gAuAp8soAH1ASgwOBwgjownw6OQTVarPRgvhiCRypmbNAnJQ3NA+BMUqwJnwAGsJIL9TyeckocoABRoe0kpRBDDJKJ0ACUXNttpAhvRsBwZA4OFgwMdbEQzWKbA9Xo4jx9BoD4EYoEdrrmHE9sj9NoDttzynzyceutABfgKYo6ZLQbLSgrsg4JDD1drHdDZAA3KAADz1eroZqgWCtWToEiaWZFScqae8h0qFqyMiNnmykugGhx+AqFuNugBA1ng1bHYDeCC4jgCSQEwI7a7eCO6DwR-Pn3nnlfrAKSPHsgoANqNgAmiYShPDULzAU8H7FgG+B4GQnwAJIUIKGEpBwkEIoM2KhAAGgA+n4AAymGhIMnjkZh2L-iWaHgBhRL4AeuFKPhhHEWRlE0XRDH5KEfjeKEngsTuf4GgAuuesqCLUHTBvMyCgkStyyJqLSQm61aOvgiA1NaBo0AAjoKlzaRCIEvG8zIjGBbBWWw8kWUUNlgus9wOXO7zjC5blFB5Mp+uyAB8-r7lc1AqFp4KyAZczGaZHZkJZQQmTUmUYqYyIqvMabKfKGmgMgnLgO4Xi+H4HDlV8Q6wrAWZcQyAwhH4zl1FFjo+o1fQDM6Bq8DBEiMAgkCyIKGiyAoygsbIkQAGLTf0t7OpILQ7LQvqxTyB4JTte0XkpaZ6GpaAPk+Jh+OhnzlL8sRfj+JjAGxHG6II5USJpkamjg63wLdz7VsCgPGp4LSPqY5gYEo5pKLAADuKhmK4b13fe353Q97FPcpKk1Gpf3INj4PsgakOwEDINgyYHCUyYoAiiKBrVKjoCMwTHGjQGkbAvy26gEGeEcIMkwkeRdEAGq6uynIAERPGkkbQDNnzK6AAD8oBgcrlkYLIFjK0EysrQg5ugMrqMmEeyvyaA4GWxE1uKaLEtSzL8uK5ybBq2QGtawCesG2wVvwB5LsR1HHksb6coKoaw1kN13iwM0M6cogvbZ-AwjCKpJxYgi0DQJnBfVq1WY7JXWe3iTZMp5guAEC85BUDQNfMyQXfUFuzhAh1jLdQAUlOJjgM95JyFP4D1CsugpA7hoO4gVe3tWo9dfVW+yALoBPDggpt3gRD95Qg+NimSiYIgjoOBwdNyGQJnbW1jCyNhgrP-934lDRkGlZDA4AaAUAGjlDev9LDSA4AAmqwDMrG3AZQAa9AfRpgDBwSAzR+hpTMBYJQ+BsxoBqg-HKplMG6hiihW0x0jymHth4Q0GUWaNQ3vmaA2wRr0IDKjDcNBzJ7gzDhNwD9OFIGwjJEsl5RHH36CYERCiIADEgFaQ6qiT5XDIAAWRghYa0k5GDf3gLAihzQX6mJ-hQegsi9zyNEU4vcyQwwmRUQox4gpeAmwcSWDwZANHGJqmhDATxjFf1mq4UJOBwlkBCc+UEmjfFkGgQMYECB2IpPgCbaIDACn+J3P4pOAZfQXWThVXeZBMJKGqPAbqvUqrZleIgTR9JGRNOKhISKdCvKHhUPQlsgpWkSAQcKd0jYWaJxlMXUmLhyap06uneqTTqxEJIS0mY7S07qi6dqdEvTYqLLQFZIINAFjVlGQaRZLZ1ksM0r5HS8A9KpSdKcrK5zFxJ36SdaptT6mNOCnUI+doJmJ1KnMluFV64HyiJyapGdG6H2LEaJAgo0Wb2RfACpwhh6dFAC0RAiBoAACF+j4BaFRGq5oghC1BPAalSNZ7LD4KsL6nwfpQoWSnHYM8EVpwngvIc5cG4F36sWca8wprwBmneSQ0gFraHPAaPASNNEQQDESkl5LECUqZeaUFtpqCn1AAAA21dAfkIBIxGhwC0WA-1+QAGYAAM7rNjQHADwNlZrZHlIUhU-Frh+i2ExHkWy28yR2HnogaeP0S7iEWZihEiBKiclDZAba3j2CJjUUEjVzsfnNx5RVHRAxVosD8BvVN6bTBeqkXnE+HBM0AHUPAtD0fgtEShHSOi0kc1FKdMUQyuMZGtabIDYPUv9GsXpsI7w3uHTF9ZY4SilMII68UmH0MxbA2sMiLwRSLoIIAA)

**Comment by dai-shi** [comment]
I think you misunderstand the usage.
https://github.com/jotaijs/jotai-trpc/blob/9751009852034759df5cd22aa915f2be039964dc/src/createTRPCJotai.ts#L142-L148
The first argument is optional `getClient`. So, you don't need to specify anything.

👉  https://tsplay.dev/Wzx4LN
<img width="769" alt="image" src="https://github.com/jotaijs/jotai-trpc/assets/490574/62cb3de1-b15b-4302-9e87-01803947d27c">


> and setting 'cartId' in Atoms layer?

Does that mean you want to set the atom value based on the mutation output??
You would be able to create a new atom then.

**Comment by drMonro** [comment]
I just tried to make construction like in '[atomWithQuery](https://prnt.sc/FgJk6wVnvaFx)', where I set parameters which is required for GET response right in Atom layer ([not inside component](https://prnt.sc/CIGYRPVa7sek)) 

How can I do the same but with 'atomWithMutation'?

**Comment by dai-shi** [comment]
Ah, I see. It wasn't a TS issue, but it's more like Jotai usage question.

I think you can create another action atom.

```js
export const cartAtom = atom({ id: '', items: [] })

const deleteFromCartAtom = api.cart.del.atomWithMutation()

export const deleteCurrentFromCurtAtom = atom(null, async (get, set) => {
  const cart = get(cartAtom)
  const output = await set(deleteFromCartAtom, {
    cartId: cart.id,
  })
  console.log(output)
})
```

**Comment by drMonro** [comment]
Oh! Ok! Thank you
I'll try this approach

**Comment by drMonro** [comment]
So, with that approach i[ can't set part of arguments](https://prnt.sc/u10G2UibDl88) on Component layer and [another part](https://prnt.sc/RwUEFg3drqqA) on Jotai layer - and i need to create 'offerIdAtom' right?

**Comment by dai-shi** [comment]
I'm not 100% following, but if it's about how to use jotai apart from jotai-trpc, it sounds about right.
